title: The Depth First Learning Fellowship
author: Depth First Learning
email: depthfirstlearning@gmail.com
description: >-
  The Depth First Learning fellowship supports researchers to build curricula
  for diving deep into machine learning topics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://depthfirstlearning.com" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
