---
label: Depth First Learning
hide_body: false
is_partial: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: false
  default: default
- type: color
  config:
    color_format: Hex
  default: "#50D4E3"
pages:
- depth-first-learning.md
